---
- hosts: localhost
  name: Dallas cDOT Configure
  connection: local
  gather_facts: false
  vars:
    user: admin
    pwd:  netapp123
    array: "hcdalnetapp"
    ansible_python_interpreter: /Users/jeorryb/virtualenvs/ansible/bin/python
    node1: "hcdalnetapp-01"
    node2: "hcdalnetapp-02"
    both_nodes: ["hcdalnetapp-01", "hcdalnetapp-02"]
    n1_sp_ip:
    n2_sp_ip:
    mgmt_submask:
    mgmt_gateway:
    n1_aggr_root_old: "aggr0"
    n1_aggr_root_new: "n1_aggr_root"
    n2_aggr_root_old: "aggr0_hcdalnetapp_02_0"
    n2_aggr_root_new: "n2_aggr_root"
    today: "01/03/2017 13:30:00"
    cluster_svm: "hcdalnetapp"
    domain: 'clinic.com'
    dns_ip: '172.16.76.140'
    ntp: '172.16.76.142'
    lic_keys: ["SKZDEWUVQFGEYAAAAAAAAAAAAAAA", "AXZHVATODUEVQEUNBPBAAAAAAAAA", "YLVLWATODUEVQEUNBPBAAAAAAAAA", "UPMTYATODUEVQEUNBPBAAAAAAAAA", "MRXWVATODUEVQEUNBPBAAAAAAAAA", "OCCTUATODUEVQEUNBPBAAAAAAAAA", "EZFMABTODUEVQEUNBPBAAAAAAAAA", "IVOEYATODUEVQEUNBPBAAAAAAAAA", "WARPXATODUEVQEUNBPBAAAAAAAAA", "GKKIZATODUEVQEUNBPBAAAAAAAAA", "MPSTTUHMISBTEEUNBPBAAAAAAAAA", "KEOXUUHMISBTEEUNBPBAAAAAAAAA", "GIFFXUHMISBTEEUNBPBAAAAAAAAA", "YJQIUUHMISBTEEUNBPBAAAAAAAAA", "AVUETUHMISBTEEUNBPBAAAAAAAAA", "QRYXYUHMISBTEEUNBPBAAAAAAAAA", "UNHQWUHMISBTEEUNBPBAAAAAAAAA", "ITJBWUHMISBTEEUNBPBAAAAAAAAA", "SCDUXUHMISBTEEUNBPBAAAAAAAAA"]
    n1_data_aggr: "n1_sata_6t_aggr0"
    n2_data_aggr:
    all_ports: [e0c]
    jumbo_ports: []
    ifgrp_name: "e0c"
    ifgrp_ports: []
    vlans: ["1560"]
    broad_dom:
      - {name: "vlan_1560 ", mtu: "1500", ports: ["hcdalnetapp-01:e0c-1560", "hcdalnetapp-02:e0c-1560"] }
    asup_dl: ["sysengineer@harbinclinic.com"]
    partner_dl: "support@n4mative.com"
    ic_lifs:
      - {name: "lif_ic_n1", vserver: "{{ array }}", node: "{{ node1 }}", port: "e0c-1560", ip: "10.70.5.14", netmask: "255.255.255.0" }
      - {name: "lif_ic_n2", vserver: "{{ array }}", node: "{{ node2 }}", port: "e0c-1560", ip: "10.70.5.15", netmask: "255.255.255.0" }
    peer_ips: ["10.70.5.12", "10.70.5.13"]
    smtp: "172.16.75.104"
    mgmt_lifs:
      - {name: "lif_nfs_svm_dr_mgmt", vserver: "{{ nfs_svm }}", node: "{{ node1 }}", port: "e0e", ip: "10.70.1.23", netmask: "255.255.255.192" }
      - {name: "lif_cifs_svm_dr_mgmt", vserver: "{{ cifs_svm }}", node: "{{ node2 }}", port: "e0e", ip: "10.70.1.24", netmask: "255.255.255.192" }
      - {name: "lif_iscsi_svm_dr_mgmt", vserver: "{{ iscsi_svm }}", node: "{{ node2 }}", port: "e0e", ip: "10.70.1.25", netmask: "255.255.255.192" }
      - {name: "lif_fcp_svm_dr_mgmt", vserver: "{{ fcp_svm }}", node: "{{ node1 }}", port: "e0e", ip: "10.70.1.26", netmask: "255.255.255.192" }
    nfs_svm: "nfs_svm_dr"
    cifs_svm: "cifs_svm_dr"
    iscsi_svm: "iscsi_svm_dr"
    fcp_svm: "fcp_svm_dr"
    data_svms:
      - {name: "{{ nfs_svm }}", vol: "nfs_svm_dr_root", aggr: "n1_sata_6t_aggr0", sec: "unix"}
      - {name: "{{ cifs_svm }}", vol: "cifs_svm_dr_root", aggr: "n1_sata_6t_aggr0", sec: "ntfs"}
      - {name: "{{ iscsi_svm }}", vol: "iscsi_svm_dr_root", aggr: "n1_sata_6t_aggr0", sec: "unix"}
      - {name: "{{ fcp_svm }}", vol: "fcp_svm_dr_root", aggr: "n1_sata_6t_aggr0", sec: "unix"}

  tasks:

    # - name: Rename n1 aggregate
    #   aggr_rename:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     aggr: "{{ n1_aggr_root_old }}"
    #     new_aggr_name: "{{ n1_aggr_root_new }}"
    #
    # - name: Rename n2 Aggregate
    #   aggr_rename:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     aggr: "{{ n2_aggr_root_old }}"
    #     new_aggr_name: "n2_aggr_root_test"
    #
    # - name: Change date time
    #   date_time:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     timezone: "America/Chicago"
    #     date: "{{ today }}"
    #
    # # - name: Change node 1 service processor ip address
    # #   sp_modify:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ node1 }}"
    # #     dhcp: "none"
    # #     ip: "{{ n1_sp_ip }}"
    # #     netmask: "{{ mgmt_submask }}"
    # #     gateway: "{{ mgmt_gateway }}"
    # #     enabled: True
    #
    # # - name: Change node 2 service processor ip address
    # #   sp_modify:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ node2 }}"
    # #     dhcp: "none"
    # #     ip: "{{ n2_sp_ip }}"
    # #     netmask: "{{ mgmt_submask }}"
    # #     gateway: "{{ mgmt_gateway }}"
    # #     enabled: True
    #
    # - name: Create dns servers for cluster svm
    #   dns_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     vserver: "{{ cluster_svm }}"
    #     domains: "{{ domain }}"
    #     dns_servers: "{{ dns_ip }}"
    #
    # - name: Create ntp server
    #   ntp_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     ntp_server: "{{ ntp }}"
    #
    # - name: Add License Keys
    #   license_add:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     license_keys: "{{ lic_keys }}"

    # - name: Create N1 data aggregate
    #   aggr_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     node: "{{ node1 }}"
    #     aggr: "{{ n1_data_aggr }}"
    #     disk_type: "FSAS"
    #     disk_count: 14
    #     disk_size: 5800g
    #     raid_size: 14
    #
    # # - name: Create N2 data aggregate
    # #   aggr_create:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ node2 }}"
    # #     aggr: "{{ n2_data_aggr }}"
    # #     disk_type:
    # #     disk_count:
    # #     disk_size:
    # #     raid_size:
    #
    # - name: Set N1 flow-control to none
    #   port_flow:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     node: "{{ node1 }}"
    #     port: "{{ item }}"
    #     flow_admin: "none"
    #   with_items: "{{ all_ports }}"
    #
    # - name: Set N2 flow-control to none
    #   port_flow:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     node: "{{ node2 }}"
    #     port: "{{ item }}"
    #     flow_admin: "none"
    #   with_items: "{{ all_ports }}"
    #
    # # - name: Set mtu to 9000
    # #   port_mtu:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ item[0] }}"
    # #     port: "{{ item[1] }}"
    # #     mtu: "9000"
    # #   with_nested:
    # #     - "{{ both_nodes }}"
    # #     - "{{ jumbo_ports }}"
    #
    # # - name: Create ifgrp a0a
    # #   ifgrp_create:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ item }}"
    # #     dist_func: "ip"
    # #     ifgrp: "{{ ifgrp_name }}"
    # #     mode: "multimode_lacp"
    # #   with_items:
    # #     - "{{ node1 }}"
    # #     - "{{ node2 }}"
    #
    # # - name: Add port to ifgrp a0a n1
    # #   ifgrp_add_port:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ node1 }}"
    # #     ifgrp: "{{ ifgrp_name }}"
    # #     port: "{{ item }}"
    # #   with_items: "{{ ifgrp_ports }}"
    #
    # # - name: Add port to ifgrp a0a n1
    # #   ifgrp_add_port:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     node: "{{ node2 }}"
    # #     ifgrp: "{{ ifgrp_name }}"
    # #     port: "{{ item }}"
    # #   with_items: "{{ ifgrp_ports }}"
    #
    # - name: Create vlan e0c-1560
    #   vlan_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     node: "{{ item[0] }}"
    #     int_name: "{{ ifgrp_name }}"
    #     vlanid: "{{ item[1] }}"
    #   with_nested:
    #     - "{{ both_nodes }}"
    #     - "{{ vlans }}"
    #
    # - name: Create broadcast domain e0c-1560
    #   broadcast_domain_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     bc_domain: "{{ item.name }}"
    #     mtu: "{{ item.mtu }}"
    #     ports: "{{ item.ports }}"
    #   with_items: "{{ broad_dom }}"
    # #
    # # - name: Modify asup
    # #   asup_modify:
    # #     cluster: "{{ array }}"
    # #     user_name: "{{ user }}"
    # #     password: "{{ pwd }}"
    # #     from_addr: "{{ item }}@harbinclinic.com"
    # #     is_node_subject: "True"
    # #     mail_host: "{{ smtp }}"
    # #     node: "{{ item }}"
    # #     partner: "{{ partner_dl }}"
    # #     to_addr: "{{ asup_dl }}"
    # #     transport: "https"
    # #   with_items: "{{ both_nodes }}"
    #
    # - name: Create intercluster lifs
    #   int_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     node: "{{ item.node }}"
    #     vserver: "{{ item.vserver }}"
    #     lif: "{{ item.name }}"
    #     role: "intercluster"
    #     port: "{{ item.port }}"
    #     ip: "{{ item.ip }}"
    #     netmask: "{{ item.netmask }}"
    #   with_items: "{{ ic_lifs }}"

    # - name: Create cluster peering relationship
    #   cluster_peer_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     remote_user: "{{ user }}"
    #     remote_pass: "{{ pwd }}"
    #     peer_addrs: "{{ peer_ips }}"

    # - name: Create vservers
    #   vserver_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     vserver: "{{ item.name }}"
    #     root_vol: "{{ item.vol }}"
    #     root_vol_aggr: "{{ item.aggr }}"
    #     security: "{{ item.sec }}"
    #   with_items: "{{ data_svms }}"

    - name: Create svm mgmt lifs
      int_create:
        cluster: "{{ array }}"
        user_name: "{{ user }}"
        password: "{{ pwd }}"
        node: "{{ item.node }}"
        vserver: "{{ item.vserver }}"
        lif: "{{ item.name }}"
        role: "data"
        port: "{{ item.port }}"
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        data_proto: "none"
      with_items: "{{ mgmt_lifs }}"
#
#    - name: Add disks
#      aggr_add:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        aggr: "n02_aggr0"
#        disk_type: "FCAL"
#        disk_count: "1"
#        disk_size: "1020m"
#
#    - name: Enable Hybrid Aggregate
#      aggr_hybrid:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        aggr: "n02_aggr0"
#        hybrid: False
#
#    - name: Set flow-control to none
#      port_flow:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        node: "atlcdot-02"
#        port: "e0d"
#        flow_admin: "none"
#
#    - name: Set mtu to 9000
#      port_mtu:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        node: "atlcdot-02"
#        port: "e0d"
#        mtu: 1500
#
#    - name: Create ifgrp a0a
#      ifgrp_create:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        node: "atlcdot-02"
#        dist_func: "ip"
#        ifgrp: "a0a"
#        mode: "multimode_lacp"
#
#    - name: Create vlan a0a-701
#      vlan_create:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        node: "atlcdot-02"
#        int_name: "e0d"
#        vlanid: "701"
#
#    - name: Create lif lif_nfs_01
    #  int_create:
    #    cluster: "{{ array }}"
    #    user_name: "{{ user }}"
    #    password: "{{ pwd }}"
    #    node: "atlcdot-02"
    #    vserver: "svm_nfs"
    #    lif: "lif_nfs_01"
    #    role: "data"
    #    port: "e0d"
    #    data_proto: ["nfs", "cifs"]
    #    ip: "172.16.199.168"
    #    netmask: "255.255.255.0"
#
#    - name: Create broadcast domain nfs
#      broadcast_domain_create:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        bc_domain: "nfs"
#        mtu: "1500"
#        ports: ["atlcdot-01:e0d"]
#
#    - name: Create subnet
#      subnet_create:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        subnet_name: "nfs"
#        bc_domain: "nfs"
#        subnet: "10.1.10.0/24"
#        ip_ranges: ["10.1.10.20-10.1.10.30", "10.1.10.60-10.1.10.70"]
#
#    - name: modify asup
#      asup_modify:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        from_addr: "admin@widgets.com"
#        is_node_subject: "True"
#        mail_host: ["smtp.widget.com"]
#        node: "atlcdot-01"
#        partner: ["support@global.com"]
#        to_addr: ["itsupport@widgets.com", "dave@widgets.com"]
#        transport: "https"
#
#    - name: Invoke asup
#      asup_invoke:
#        cluster: "{{ array }}"
#        user_name: "{{ user }}"
#        password: "{{ pwd }}"
#        node: "atlcdot-01"
#        message: "Test asup"
#        asup_type: "test"

    # - name: Create vserver for CIFS
    #   vserver_create:
    #     cluster: "{{ array }}"
    #     user_name: "{{ user }}"
    #     password: "{{ pwd }}"
    #     vserver: "svm_cifs"
    #     root_vol: "svm_cifs_root"
    #     root_vol_aggr: "n1_aggr0"
    #     security: "ntfs"



...
